### ISSUE TITLE
About this gamemode

### ISSUE THREAD

**Issue by pushline** [WeponzTV/dojrp_samp#1]
Plz delete, it's trash.

**Comment by WeponzTV** [comment]
Go make something even close to the level of this script.. after reviewing your repositories I'll be waiting a very long time.

**Comment by Mortyyka** [comment]
fortnite battlepass

**Comment by pushline** [comment]
i just shit at my ass

**Comment by Mortyyka** [comment]
booted up mah pc

**Comment by Mortyyka** [comment]
to get that fortnite battlepass

**Comment by pushline** [comment]
i llike Fortnite

**Comment by wweziza** [comment]
@brolysan2748
1 month ago
Man do you have any teleport/fly/troll hack anti cheat?

**Comment by Mortyyka** [comment]
SIR YOU ARE A LIAR YOU SAID ITS COMPLETED BUT IT ISN'T DELETED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by pushline** [comment]
The human being is retardedd
