### ISSUE TITLE
What is this mess?

### ISSUE THREAD

**Issue by DobbysGamertag** [WeponzTV/dojrp_samp#3]
https://github.com/WeponzTV/dojrp_samp/blob/4f0c4a33bf1d2863b0e911a965f78295f575213c/gamemodes/DOJRP/player/locations.inc#L378

**Comment by FreddieCrew** [comment]
This whole shitshow is a mess, and honestly, the more I look into his code, the more I wanna blow my brains out.

**Comment by WeponzTV** [comment]
What do you mean? Me choosing to call a function from within a module to use elsewhere (in other modules) instead of just using the raw enumerator value just because you can? Get a life man lmao

**Comment by FreddieCrew** [comment]
> It's not complete. Do you not understand basic programming?

He clearly does not.
